######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 7 17:03:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AirborneRadarQC.h \
           Dorade.h \
           precision.h \
           read_dorade.h \
           RecursiveFilter.h
SOURCES += AirborneRadarQC.cpp Dorade.cpp main.cpp RecursiveFilter.cpp
