source "http://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "shoulda", ">= 0"
  gem "bundler", ">= 1.2.0"
  gem "jeweler", ">= 2.0.1"
  gem "simplecov", ">= 0"
  gem "rake-compiler", ">= 0.7.9"
  gem "rice", ">=  1.6.0"
  gem "rdoc", ">= 2.4.2"
end
