# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radarqc}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Bell", "Cory Wolff"]
  s.date = %q{2011-07-29}
  s.description = %q{This code is part of a project for meteorological data quality control of airborne tail Doppler radars. This gem interfaces with C++ code to provide command line scripting functionality for the QC procedures. The project is sponsored by the National Science Foundation and the National Center for Atmospheric Research.}
  s.email = %q{michaelmbell@gmail.com}
  s.extensions = ["ext/QCscript/extconf.rb"]
  s.files = [
    "ext/QCscript/AirborneRadarQC.cpp",
    "ext/QCscript/AirborneRadarQC.h",
    "ext/QCscript/Dorade.cpp",
    "ext/QCscript/Dorade.h",
    "ext/QCscript/Makefile",
    "ext/QCscript/QCscript.cpp",
    "ext/QCscript/QCscript.h",
    "ext/QCscript/RecursiveFilter.cpp",
    "ext/QCscript/RecursiveFilter.h",
    "ext/QCscript/extconf.rb",
    "ext/QCscript/precision.h",
    "ext/QCscript/read_dorade.h",
    "lib/radarqc.rb"
  ]
  s.homepage = %q{http://github.com/mmbell/Airborne-Radar-QC/radarqc}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Scripted data quality control for meteorological radars}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

