# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
jeweler_tasks = Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "radarqc"
  gem.homepage = "http://github.com/mmbell/Airborne-Radar-QC/radarqc"
  gem.license = "MIT"
  gem.summary = %Q{Scripted data quality control for meteorological radars}
  gem.description = %Q{This code is part of a project for meteorological data quality control of airborne tail Doppler radars. This gem interfaces with C++ code to provide command line scripting functionality for the QC procedures. The project is sponsored by the National Science Foundation and the National Center for Atmospheric Research.}
  gem.email = "michaelmbell@gmail.com"
  gem.authors = ["Michael Bell", "Cory Wolff"]
  gem.extensions = FileList["ext/**/extconf.rb"]
  gem.files.include('lib/radarqc/QCscript.*')
  gem.files.include('lib/**/*')
  gem.files.include('lib/qt/qmake.rb')  
  gem.files.include('ext/**/*')
  # dependencies defined in Gemfile
end
Jeweler::RubygemsDotOrgTasks.new
gemspec = jeweler_tasks.gemspec
gemspec.version = jeweler_tasks.jeweler.version

require 'rake/extensiontask'
Rake::ExtensionTask.new('QCscript',gemspec)

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

require 'rcov/rcovtask'
Rcov::RcovTask.new do |test|
  test.libs << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
  test.rcov_opts << '--exclude "gems/*"'
end

task :default => :test

require 'rdoc/task'
RDoc::Task.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "radarqc #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
